DROP TABLE IF EXISTS purchase_orders;
DROP TABLE IF EXISTS inventory_items;

CREATE TABLE inventory_items (
    id VARCHAR(20) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    stock INT NOT NULL CHECK (stock >= 0),
    version BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE purchase_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id VARCHAR(30) NOT NULL UNIQUE,
    product_id VARCHAR(20) NOT NULL,
    quantity INT NOT NULL CHECK (quantity > 0),
    CONSTRAINT fk_purchase_inventory
        FOREIGN KEY (product_id) REFERENCES inventory_items(id)
);
